Added support for changing the prefix key configuration
MentorEmbedded/mtda pull request #22
Opened 2020-10-23 12:10 UTC by hkoturap

2020-10-26 05:12 UTC, hkoturap commented
@chombourger ,
By default in BBB build we will not have all fields defined in https://github.com/MentorEmbedded/mtda/blob/master/mtda.ini.  Added newly prefix field under remote section. Request your feedback on same.

2020-10-26 05:32 UTC, chombourger commented on mtda-cli
> +        key = client.console_prefixkey()
`prefix_key = client.console_prefix_key()`

2020-10-26 05:34 UTC, chombourger commented on mtda-cli
> +            prefix = self.console_getprefix(key)
does not appear to be required since we have already checked what the prefix key is (just a few lines above)

2020-10-26 05:34 UTC, chombourger commented on mtda-cli
> +            if c == prefix:
`if c == prefix_key:`

2020-10-26 05:35 UTC, chombourger commented on mtda-cli
> -                server.console_send(c, True)
we need to send other keys to the console. this line shouldn't be removed

2020-10-26 05:35 UTC, chombourger commented on mtda-cli
> +    def console_getprefix(self, prefixkey):
`def console_set_prefix_key(self, prefix_key):`

2020-10-26 05:35 UTC, chombourger commented on mtda-cli
> +        print("The control prefix key specified is %s" %prefixkey)
remove print

2020-10-26 05:36 UTC, chombourger commented on mtda-cli
> +        print("The control prefix key specified is %s" %prefixkey)
add something like `prefix_key = prefix_key.lower()`

2020-10-26 05:38 UTC, chombourger commented on mtda-cli
> +            print("\r\nthe prefix key is not supported\r\n")
raise a ValueError instead. message should include the specified `prefix_key`

2020-10-26 05:40 UTC, chombourger commented on mtda-cli
> +        key_dict = {'Ctrl-a' : '\x01' , 'Ctrl-b' : '\x02' , 'Ctrl-c' : '\x03' , 'Ctrl-d' : '\x04',
here we should lower case all valid ctrl keys (e.g. `Ctrl-a` -> 'ctrl-a')
we should also remove keys that conflict with other keys (e.g. `Ctrl-m` is also the return key)

2020-10-26 05:42 UTC, chombourger commented on mtda-cli
> +            print("\r\nthe prefix key is not supported\r\n")
move of the above code should go in a `load_ui_config()` method to be loaded from `load_config` when a `ui` section is found

2020-10-26 05:42 UTC, chombourger commented on mtda.ini
> +# prefix = Ctrl-a
should really be added to a `ui` section

2020-10-26 05:43 UTC, chombourger commented on mtda/main.py
> +        self.ctrlprefix = 'Ctrl-a'
self.prefix_key for consistency

2020-10-26 05:44 UTC, chombourger requested changes
code to be restructured per comments

2020-10-27 05:44 UTC, hkoturap commented on mtda-cli
> +        key = client.console_prefixkey()
corrected.

2020-10-27 05:46 UTC, hkoturap commented on mtda-cli
> +            prefix = self.console_getprefix(key)
Added comment correctly.Here we get key defined and below we get ascii value corresponding to key defined.

2020-10-27 05:47 UTC, hkoturap commented on mtda-cli
> +            if c == prefix:
updated with correct value.

2020-10-27 05:47 UTC, hkoturap commented on mtda-cli
> -                server.console_send(c, True)
Corrected.

2020-10-27 05:49 UTC, hkoturap commented on mtda-cli
> +        print("The control prefix key specified is %s" %prefixkey)
Done.

2020-10-27 05:50 UTC, hkoturap commented on mtda.ini
> +# prefix = Ctrl-a
Added a new section in ini file for ui section and added prefix key under it.

2020-10-27 05:51 UTC, hkoturap commented on mtda/main.py
> +        self.ctrlprefix = 'Ctrl-a'
corrected

2020-10-27 05:54 UTC, hkoturap commented on mtda-cli
> +        key_dict = {'Ctrl-a' : '\x01' , 'Ctrl-b' : '\x02' , 'Ctrl-c' : '\x03' , 'Ctrl-d' : '\x04',
@chombourger In case of these keys like 'ctrl-m" we shouldnt support these keys?

2020-10-27 05:54 UTC, hkoturap commented on mtda-cli
> +            print("\r\nthe prefix key is not supported\r\n")
Done

2020-10-27 05:55 UTC, hkoturap commented on mtda-cli
> +    def console_getprefix(self, prefixkey):
Done

2020-10-27 05:58 UTC, chombourger commented on mtda-cli
> +        key_dict = {'Ctrl-a' : '\x01' , 'Ctrl-b' : '\x02' , 'Ctrl-c' : '\x03' , 'Ctrl-d' : '\x04',
correct. if you type ctrl-m in your terminal, you will see that it is interpreted as the return key

2020-10-27 06:01 UTC, chombourger commented on mtda-cli
> +    def console_set_prefix_key(self, prefix_key):
we don't really need to expose this method to the outside world.  it is also not setting anything
let's change this to: `def _prefix_key_code(self, prefix_key)`

2020-10-27 06:04 UTC, chombourger commented on mtda/main.py
> +            parser.get('ui', 'prefix', fallback=self.prefix_key))
```
self.prefix_key = self._prefix_key_code(parser.get('ui', 'prefix', fallback=DEFAULT_PREFIX_KEY))
```

2020-10-27 06:05 UTC, chombourger commented on mtda/main.py
> +        self.prefix_key = 'ctrl-a'
```
self.prefix_key = self._prefix_key_code(DEFAULT_PREFIX_KEY)
```

2020-10-27 12:39 UTC, chombourger commented on mtda.ini
> +# Set "prefix" to the key which should be followed by command key for controling from interactive console.
add line feeds so we do not exceed the dotted line below

2020-10-27 12:39 UTC, chombourger commented on mtda.ini
> +# Set "prefix" to the key which should be followed by command key for controling from interactive console.
add line feeds so we do not exceed the dotted line below

2020-10-27 12:40 UTC, chombourger commented on mtda/main.py
> +        self.default_prefix_key = 'ctrl-a'
should declared at the top of this file as a global
```
DEFAULT_PREFIX_KEY = 'ctrl-a'
```

2020-10-27 12:40 UTC, hkoturap commented on mtda-cli
> +            print("\r\nthe prefix key is not supported\r\n")
Moved it to _prefix_key_code under main.py

2020-10-27 12:40 UTC, chombourger commented on mtda/main.py
> +        self.is_remote = self.remote is not None
copy & paste error? shouldn't be needed

2020-10-27 12:41 UTC, hkoturap commented on mtda-cli
> +        key_dict = {'Ctrl-a' : '\x01' , 'Ctrl-b' : '\x02' , 'Ctrl-c' : '\x03' , 'Ctrl-d' : '\x04',
Presently have removed ctrl-m

2020-10-27 12:42 UTC, hkoturap commented on mtda-cli
> +    def console_set_prefix_key(self, prefix_key):
Changed it and moved it to main.py

2020-10-27 12:43 UTC, hkoturap commented on mtda/main.py
> +            parser.get('ui', 'prefix', fallback=self.prefix_key))
Done

2020-10-27 12:47 UTC, hkoturap commented on mtda/main.py
> +        self.prefix_key = 'ctrl-a'
As we initialize self.prefix_key with fallback value in-case of ui section not defined, presently have not called again _prefix_key_code. Should this be corrected?

2020-10-27 12:51 UTC, chombourger commented on mtda/main.py
> +        self.prefix_key = 'ctrl-a'
I believe this would be more correct because this member variable would never hold the string describing the prefix key but rather its ASCII code

2020-10-27 13:42 UTC, hkoturap commented on mtda.ini
> +# Set "prefix" to the key which should be followed by command key for controling from interactive console.
Done

2020-10-27 13:43 UTC, hkoturap commented on mtda/main.py
> +        self.default_prefix_key = 'ctrl-a'
Done

2020-10-27 13:43 UTC, hkoturap commented on mtda/main.py
> +        self.is_remote = self.remote is not None
Corrected

2020-10-27 13:43 UTC, hkoturap commented on mtda.ini
> +# Set "prefix" to the key which should be followed by command key for controling from interactive console.
Done

2020-10-27 13:48 UTC, chombourger approved these changes

2020-10-27 13:48 UTC, merged